### ISSUE TITLE
Zaključevanje

### ISSUE THREAD

**Issue by kokosinekm** [Marsovc1/APPR-2019-20#1]
Projekt, mislim da je zaključen razen shiny interaktivnega zemljevida. Je možno, da preverite ali je vredu?

**Comment by jaanos** [comment]
Poročilo se prevede, tako da bom kar dodal povezavo na repozitorij za zagovore. Če se še nisi, se lahko z @alenFMF domeniš za termin zagovora. Če boš do takrat še kaj spreminjal, mi javi, da posodobim povezavo.

Imam še par pripomb:

* Pri prvih dveh grafih se pri oznaki osi z letnicami pojavljajo polovice. Najlažje bo, če sam določiš, katere oznake naj se prikažejo - npr. tako, da grafoma prišteješ še `scale_x_continuous(breaks=seq(2010, 2020, 2))`.

* Program `vizualizacija.r` kličeš dvakrat - drugič brez parametra `results='hide'`, tako da se ti v poročilo izpiše neželeno obvestilo. Drugi klic torej odstrani.

**Comment by kokosinekm** [comment]
Hvala za komentar, sem dopolnil.

**Comment by jaanos** [comment]
V redu, sem posodobil povezavo.
